# Generated by Django 6.0.5 on 2026-05-13 13:33

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('name', models.CharField(max_length=255)),
                ('is_folder', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_trashed', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('FOLDER', 'Folder'), ('OTHER', 'Other')], default='OTHER', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('share_mode', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('PUBLIC', 'Public')], default='RESTRICTED', max_length=15)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.cloudfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='core.cloudfile')),
            ],
        ),
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('EDITOR', 'Editor')], default='VIEWER', max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='core.cloudfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_limit_bytes', models.BigIntegerField(default=53687091200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cloudfile',
            index=models.Index(fields=['user', 'is_trashed', 'parent'], name='core_cloudf_user_id_b400e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudfile',
            index=models.Index(fields=['user', 'is_trashed', 'is_folder', '-last_viewed_at'], name='core_cloudf_user_id_43ff10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessrequest',
            unique_together={('file', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='fileaccess',
            unique_together={('file', 'user')},
        ),
    ]
